### ISSUE TITLE
Log4J implementation

### ISSUE THREAD

**Issue by remipe-utbm** [Jeodd/TeachMe#6]
Set up log4J
Do we need a system of annotations?

**Comment by Jeodd** [comment]
Are you waiting for an answer ?

**Comment by Jeodd** [comment]
Just attaching commit to issue : 31ea1f8ec8680ea0414c9b4cebee8cb9a3233683

**Comment by remipe-utbm** [comment]
Re install log4J in projet (bad path)

Add some log4J logs into DAOs and HibernateUtils class.
